### ISSUE TITLE
Basic snapshot/restore through dumps stored in S3 bucket

### ISSUE THREAD

**Issue by gberche-orange** [krujos/data-lifecycle-service-broker#3]
Thanks for sharing this great idea and codebase in the [cf summit session](https://www.youtube.com/watch?v=mQFKr5S7Bhc&index=16&list=PLekKnRxI5BKsDMoBTG6SlwlkTlads4KUa). I find interesting the idea of materializing dumps as service instances. We're planning on trying to the data-lifecycle-service-broker to propose a basic way for our user to perform the proposed tasks:
- backup/restore of a given db service instance (plan "restore")
- snapshot of a given db service instance, and then cloning it into a new service instance (adding the anonymisation step, plan "clone")

We're thinking to start with a basic approach suiteable for low volume dbs that would use the standard clients to dump the content of the service instance into a S3 bucket, and then restore into an existing instance or create a new instance from this dump. This approach is therefore iaas independent, and appliceable to a large set of dbs, provided their clients provides the ability to dump its content into a file.

More specifically, to start with the case of a p-mysql service instance, the first prototype could be as follow:
a custom fork of the data-lifecycle-service-broker broker (as a cf app) with 3 bound services:
- a source p-mysql database service instance we want to make a copy of (this corresponds to the instanceId passed into https://github.com/krujos/data-lifecycle-service-broker/blob/master/src/main/java/org/cloudfoundry/community/servicebroker/datalifecycle/provider/CopyProvider.java  which is currently supposed to be provided by a specific env variable)
- an S3 endpoint for storing backup/snapshot dumps 
- a user-provided-service containing the credentials of a cloudfoundry account (user/password) allowing to make calls to the CC API to create new service instances (using the cf-java-client)

This custom fork of the data-lifecycle-service-broker would do the following:
- when the `provision` phase is called (i.e. translating to a call to https://github.com/krujos/data-lifecycle-service-broker/blob/master/src/main/java/org/cloudfoundry/community/servicebroker/datalifecycle/provider/CopyProvider.java  ), the CopyProvider impl would use mysql dump to dump the bound p-mysql service instance into a S3 bucket, and return the Id of this bucket. As to avoid reaching the cf app ephemeral disk and RAM limits, optimization such as streaming the dump to S3 using multipart uploads.

With the "clone" service plan:
- when the `bind instance` is called (i.e. translating into a call to https://github.com/krujos/data-lifecycle-service-broker/blob/master/src/main/java/org/cloudfoundry/community/servicebroker/datalifecycle/provider/CopyProvider.java ), it extracts the app guid from https://github.com/cloudfoundry-community/spring-boot-cf-service-broker/blob/fd81650388d25ca38d97a9e0b5777b33d8a6ce01/src/main/java/org/cloudfoundry/community/servicebroker/model/CreateServiceInstanceBindingRequest.java  and uses the  cf-java-client/cc api to lookup in which space this app is currently deployed. It then calls the cc api to do an equivalent of "cf target -s this space; cf cs p-mysql 100mb mysql-copy". It then retreives the credentials of the created mysql (through the upcoming broker service key feature[1], or binding a fake app just to get access to the bound service credentials through “cf env” cc api call equivalent), and connects the mysql dump to restore the dump stored in the S3 bucket. It returns the service key credentials in the credentials
- when the `unbind instance` is called, it uses the cc api to delete the p-mysql mysql-copy instance, 
- when the `delete instance` is called, it removes the bucket from S3

With the "restore" service plan:
- when the bind instance is called (i.e. translating into a call to https://github.com/krujos/data-lifecycle-service-broker/blob/master/src/main/java/org/cloudfoundry/community/servicebroker/datalifecycle/provider/CopyProvider#getCreds() it imports the dump from the specific S3 bucket into the original db, and returns the original creds
- when the `unbind instance` is called, it does nothing
- when the `delete instance` is called, it simply removes the bucket from S3 bucket

Pending limitations of this approach: there is a need to have a service broker registered in the marketplace for each source service instance we want to backup/restore snapshot/clone, which is cumbersome, pollutes the marketplace, and causes confidentiality issues.

A potential evolution, once the arbirary service params feature would be out, would be to have a unique service broker, and pass to it a source db service instance binding guid (or alternatively a spaceid, service instance name, and an app name), and the broker would dynamically lookup the associated credentials to perform the dump.

[1] https://docs.google.com/document/d/1rHH-QeMKHEksLoFKYh3XfzSY3EBgQCf-tFoj0SF0a7Q/edit?usp=sharing 

I am keen on exchanging on this idea, and get feedback prior to sending a PR once the prototype is working.

**Comment by krujos** [comment]
Hi @gberche-orange, thanks for submitting this! I'm excited to collaborate. I'm still chewing on it and anticipate some more in depth comments soon! I wanted to point you to the branch where I'm breaking out changes, as that will hopefully allow for an easier extension model and get your thoughts. Ideally we can have fewer forks and compose services brokers. 

The big thing that's jumping out at me is your need to specify a different catalog endpoint (that probably just works by having an @Service w/ higher priority, but I'm not 100% sure). The time constraints we're under with binding (those apis are still sync, so must complete in 60 seconds) also concern me. Are you proposing to do the data movement from S3 during the cf bind-service step? 

You're right on about the limitations, this is one of the limitations of my design and implementation, it's too tied to the data they broker when you start to do "real" work. I think Brooklyn has some elegant solutions to this and may be one avenue of investigation down the road, or something like Eureka. 

Here's the branch!
https://github.com/krujos/data-lifecycle-service-broker/tree/deconstruct

Still reading and thinking! I like what you're proposing.

**Comment by krujos** [comment]
Okay, so chewing on it a bit more. The restore use case is one I'd like to understand better. I'm not sure I'm clear on what you're trying to achieve there. It reads to me as if you overwrite the source data, and then delete the copy? Can you tell me more about what you're trying to achieve from a user perspective?

**Comment by gberche-orange** [comment]
Thanks for your feedback, and pointing the inconsistencies in the "restore" plan during unbind. I've editted the initial proposal to fix this.

One use-case for the restore plan is:
- before deploying a new version of an application, app-ops want to perform a backup of their db
- the new version of the application is deployed (which alters the db schema and db content)
- if the deployment shows regressions, they can restore the backup, and rollback to initial app version.

In this case, the usage of the service broker would be as follow:
- create data-sb instance (service plan=restore), called "backup-before-upgrade-to-version-n"
- deploy app version N+1
- watch app metrics. As they show unacceptable regression, decide to rollback
- create data-sb instance (service plan=restore), called "backup-on-version-n-plus1-before-rollback-to-n"
- bind data-sb instance "backup-before-upgrade-to-version-n"
- rollback app to version N

One missing use-case would be to clone data-sb instance "backup-on-version-n-plus1-before-rollback-to-n" in order to reproduce/diagnose in dev. I see that possible in the future if the "binding params" (mentionned at a time on vcap-dev) finally get implemented. In which case, the service broker would expose a single plan, and depending the binding parameter would perform a clone or a restore action.

I also share your concern w.r.t. the current 60s bind duration limit: it might indeed be too short for some large S3-based dumps to be imported. In terms of alternatives:
1. having the `bind` and `unbind` also be async. But not clear this would come any time soon as it might not be useful to other traditional brokers
2. split the broker in two brokers: 
   - a "data-dump-broker" that only performs dumps. 
   - an "import-dump-broker" that accept the dump in bind arbitrary service param, with two service plans, or potentially it self split in two brokers:
     - a "restore-dump-to-existing-instance" broker
     - a "restore-dump-to-new-instance" broker

The later solution seems more realistic and flexible, and supports the use-case of cloning a "backup" instead of being forced to "restore" it. The main downside being the need to pass in arbitrary service params in json, which may require a CLI plugin to make it user-friendly and productive.

I'm not sure I understand your comments about the Brooklyn and Eureka, I'll watch their summit session now.

Also I don't understand your comment about having two service endpoints (I was originally thinking of a single endpoint exposing two service plans "clone" and "restore" service plans.

Thanks again,

Guillaume.

**Comment by krujos** [comment]
I'd like to suggest an alternative implementation that may fit within the existing service broker architecture a bit better. Create a service broker which makes a full clone / copy of a target upon service provisioning (cf create-service plan=copy) and loads it into an other database. 

For example: 
1 cf create-service NewBroker Copy NewInstance
1.1 NewBroker does a mysql dump to s3 of it's production instance
1.2 NewBroker creates a new MySQL instance (this could use the existing MySQL broker)
1.3 NewBroker does a db load based on info from the new instance.
2 cf push app-v2 --no-start
3 cf bind-service app-v2 NewInstance
4 cf start app-v2
5 migrations etc happen now. 
6 cf stop app-v1

This has a couple of advantages. The first is that recovery is an explicit action, not a side effect. The second is that recovery is much simpler and much quicker. In a rollback scenario, simply delete app-v2 and restart app-v1. When you're satisfied that app-v2 is healthy, you can delete app v1 and the associated service instance. Thirdly, it fits within the existing async framework. Lastly, it gives you the clone case that was missing. 

If I were implementing this I think I'd try to proxy the p-mysql broker for all the creation and binding logic, and insert the copy code in between. Theres some credentials issues to sort through there, can one broker know anthers password, or are we actually brokering the db creds (which is what I'm doing in my implementation from summit).

Thoughts? Would this work better for you? It feels a bit easier to me to implement and for users to consume. 

My other comments. The framework (data-lifecycle-service-broker) presents a catalog via an @service annotation. For your use case you would need to supply your own. I'd not thought about that previously and you pointed out a gap. I believe it will be easy to address, I'd just not thought of it. 

Brooklyn and Eureka seem like good ways to avoid having to deploy a broker per database, but I think that's a future problem.

**Comment by gberche-orange** [comment]
This model (full clone on "provision") seems simpler, with the following trade-offs:
- a given S3 dump can only be instanciated once, and is only used as transient storage between dump and import. This could as well be a streamed export dump to import without S3 storage.
- it's potentially much more expensive to keep p-mysql instances up as snapshot "in case something happens", than having S3 buckets as cold snapshots (a p-mysql instance would typically use high IOPS storage, replicated within the galera cluster), plus mysql import statement might be slow to execute "just-in-case)

**Comment by krujos** [comment]
Point 1: If your desire is to have a persistent backup then you need to store it outside the system. So yes you could streamline it, but then you loose the backup. 

Point 2: depends on how long it takes you to figure out something went wrong and if you can accept the downtime or degraded performance (not knowing the apps I can only speak in the abstract, which makes me dangerous :)). If you're doing immediate cut overs to the new then you could delete the database straightaway and only restore if there was an issue. Your trading cost for risk there.

**Comment by gberche-orange** [comment]
I refined the idea above in a [design document](https://docs.google.com/document/d/1Y5vwWjvaUIwHI76XU63cAS8xEOJvN69-cNoCQRqLPqU/edit): detailing requirements, and possible designs.

I'd be happy to get thoughts on this, improvements, whether this could be useful for the community. Feel free to comment in the google doc, or continue high-level conversation here.
